NAME = minishell

src = bulit.c execution.c re_libft.c small_libft.c split.c split_with_slash.c utils1.c utils2.c  main.c days/d00.c days/d01.c days/d02.c days/d03.c days/d04.c	
run : 
	gcc -lreadline $(src) -o $(NAME) -fsanitize=address	-g3 


